### PR TITLE
testing/grpc: new aport

### PR DESCRIPTION
**Pull request by wenerme**
options="!check" because test is way too complex to run, required a lot different languages, tools.

this package depends on gflags https://github.com/alpinelinux/aports/pull/3687

grpc-cli: most time, grpc-cli is not needed, grpc-cli is a util for debug grpc service.

### CODE REVIEW

**Comment by jirutka** [comment]
⚠️ grpc must be very thoroughly reviewed if it does not bundle some libs or CA certificates as grpc-ruby do (see https://github.com/jirutka/user-aports/tree/v3.7/user/ruby-grpc). ⚠️

**Comment by wenerme** [comment]
@jirutka Why grpc have to bundle libs or CA certificates ?

**Comment by jirutka** [comment]
@jirutka Why grpc have to bundle libs or CA certificates ?

It does not _have to_ bundle, it definitely _should not_ bundle them, but they still do, because Google… 😕

**Comment by wenerme** [comment]
I found `/usr/share/grpc/roots.pem` in final apk, should this included in package ?

**Comment by jirutka** [comment]
> I found `/usr/share/grpc/roots.pem` in final apk, should this included in package ?

No, should not be.

**Comment by wenerme** [comment]
DONE, ca has been removed

File: testing/grpc/APKBUILD [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+unpack() {
+	default_unpack
+	cd "$srcdir"
+	rm -rf $pkgname-$pkgver/third_party/googletest
+	ln -sfn $PWD/googletest-$_googletest_rev/ $pkgname-$pkgver/third_party/googletest
+}
+
+build() {
+	cd "$builddir"
+	make -j$(nproc)
```
Comment (ncopa) [inline testing/grpc/APKBUILD]: you dont need to (and should not) set `-j$(nproc)` because we set this in `/etc/abuild.conf`:
````
export JOBS=20
export MAKEFLAGS="-j$JOBS"
````

File: testing/grpc/APKBUILD [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+
+package() {
+	cd "$builddir"
+	make install prefix="$pkgdir/usr" -j$(nproc)
+	rm -f "$pkgdir/usr/share/grpc/roots.pem"
+}
+
+cli() {
+	cd "$builddir"
+	make install-grpc-cli prefix="$subpkgdir/usr" -j$(nproc)
```
Comment (ncopa) [inline testing/grpc/APKBUILD]: same here. don't set `-j$(nproc)`

File: testing/grpc/APKBUILD [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+pkgver=1.10.0
+pkgrel=0
+pkgdesc="The C based gRPC (C++, Python, Ruby, Objective-C, PHP, C#) "
+url="https://grpc.io/"
+giturl="https://github.com/grpc/grpc"
+arch="all"
+license="Apache2"
+depends="protobuf"
+depends_dev="protobuf-dev"
+makedepends="autoconf automake libtool libstdc++ protobuf-dev c-ares-dev openssl-dev gflags-dev gtest-dev zlib-dev yaml-dev"
```
Comment (ncopa) [inline testing/grpc/APKBUILD]: We should use `libressl-dev` instead of `openssl-dev`

**Comment by ncopa** [comment]
it fails to build with libressl 2.6:
````
src/core/lib/security/credentials/jwt/jwt_verifier.cc: In function 'EVP_PKEY* pkey_from_jwk(const grpc_json*, const char*)':
src/core/lib/security/credentials/jwt/jwt_verifier.cc:526:47: error: 'RSA_set0_key' was not declared in this scope
   if (!RSA_set0_key(rsa, tmp_n, tmp_e, nullptr)) {
                                               ^
````

but I think it will build just fine with libressl 2.7, which I am working on now

**Comment by wenerme** [comment]
So, should I just wait 2.7 to fix the pr

**Comment by ncopa** [comment]
yes, lets wait til after libressl-2.7 (may take a few days).

I can confirm that it builds with libressl 2.7

**Comment by andypost** [comment]
Looks 2.7 stabilized

**Comment by andypost** [comment]
Btw 1.10 is herehttps://github.com/alpinelinux/aports/blob/master/testing/grpc/APKBUILD 

And 1.11 releasedhttps://github.com/grpc/grpc/releases/tag/v1.11.0

**Comment by wenerme** [comment]
I close this pr now , creata another version upgrade pr.
