### PR TITLE
community/ffmpeg: upgrade to 4.0.1

### PR DESCRIPTION
**Pull request by 9001**
also enables the FATE test suite

### CODE REVIEW

**Comment by andypost** [comment]
Duplicates https://github.com/alpinelinux/aports/pull/4079

**Comment by andypost** [comment]
Otoh most of it makes sense

**Comment by 9001** [comment]
FATE was failing because the libraries are expected at /usr/lib. The 2nd commit sets LD_LIBRARY_PATH to the relevant locations within the build directory. Figured this was good enough since it strictly affects the test suite... Is this acceptable or do we want a cleaner approach?

(and I'll remember to check the pending pull requests next time!)

**Comment by ncopa** [comment]
seems like it breaks the ABI so a bunch of packages will need to be rebuilt.

**Comment by ncopa** [comment]
`community/guvcview` fails with:
````
uvc_h264.c: In function 'h264_init_decoder':
uvc_h264.c:1008:2: warning: 'avcodec_register_all' is deprecated [-Wdeprecated-declarations]
  avcodec_register_all();
  ^~~~~~~~~~~~~~~~~~~~
In file included from uvc_h264.c:41:0:
/usr/include/libavcodec/avcodec.h:4086:6: note: declared here
 void avcodec_register_all(void);
      ^~~~~~~~~~~~~~~~~~~~
uvc_h264.c:1042:31: error: 'CODEC_FLAG2_FAST' undeclared (first use in this function)
  h264_ctx->context->flags2 |= CODEC_FLAG2_FAST;
                               ^~~~~~~~~~~~~~~~
````

**Comment by ncopa** [comment]
seem like there are more pacakges that has problems with the ffmpeg 4.0 API. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227748

**Comment by 9001** [comment]
Should we split into ffmpeg3 and ffmpeg4? Looks like gst-libav is working on supporting 4.0.x however Firefox is another notable holdback. Related: https://github.com/voidlinux/void-packages/issues/14058

**Comment by prspkt** [comment]
[Patch](https://github.com/void-linux/void-packages/blob/881346137bb1de90de3906b323afd5f0541bb8fe/srcpkgs/guvcview/patches/ffmpeg4.patch) for `community/guvcview`

**Comment by andypost** [comment]
needs rebase

**Comment by nmeum** [comment]
Any news on this? We should definitely include this in the next release. I also noticed that we can't upgrade to the latest mpv version unless we upgrade ffmpeg first as [mpv v0.29.0](https://github.com/mpv-player/mpv/releases/tag/v0.29.0) requires `FFmpeg 4.0 or newer` (probably affects other packages as well).
