### PR TITLE
main/protobuf: upgrade to 3.3.2 and add subpackage ruby-google-protobuf

### PR DESCRIPTION
**Pull request by jirutka**
Depending packages needs to be rebuild!

**Problems with depending packages:**

- [x] community/bitcoin: fails to build due to incorrect source checksum (what happened?!) [UPDATE: works now]
- [ ] community/namecoin: fails to build due to incorrect source checksum (what happened?!)
- [x] community/rethinkdb: fails to build: [UPDATE: works with protobuf 3.3.2]
    ```
        [12/423] CP ./build/drivers/ruby/lib
    [libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: rdb_protocol/ql2.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
        [14/423] BUILD re2_20140111
        [13/423] CC build/release_system/obj/web_assets/web_assets.o
        [15/423] CC build/release_system/obj/rdb_protocol/ql2.pb.o
    build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* VersionDummy::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
    build/proto/rdb_protocol/ql2.pb.cc:1123:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
         bool deterministic, ::google::protobuf::uint8* target) const {
              ^~~~~~~~~~~~~
    build/proto/rdb_protocol/ql2.pb.cc: In member function 'virtual google::protobuf::uint8* Frame::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
    build/proto/rdb_protocol/ql2.pb.cc:2470:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
         bool deterministic, ::google::protobuf::uint8* target) const {
              ^~~~~~~~~~~~~
    cc1plus: all warnings being treated as errors
    make[1]: *** [src/build.mk:387: build/release_system/obj/rdb_protocol/ql2.pb.o] Error 1
    ```
- [ ] testing/ostinato: fails to build:
    ```
    g++ -c -pipe -O2 -fPIC -D_REENTRANT -Wall -W -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtScript -I/usr/include -I../extra/qhexedit2/src -I. -I. -o moc_ipv6addressdelegate.o moc_ipv6addressdelegate.cpp
    fileformat.pb.cc: In member function 'virtual google::protobuf::uint8* OstProto::FileMetaData::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
    fileformat.pb.cc:600:10: warning: unused parameter 'deterministic' [-Wunused-parameter]
         bool deterministic, ::google::protobuf::uint8* target) const {
              ^~~~~~~~~~~~~
    fileformat.pb.cc: In member function 'virtual google::protobuf::uint8* OstProto::FileMagic::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
    fileformat.pb.cc:2198:10: warning: unused parameter 'deterministic' [-Wunused-parameter]
         bool deterministic, ::google::protobuf::uint8* target) const {
              ^~~~~~~~~~~~~
    g++ -c -pipe -O2 -fPIC -D_REENTRANT -Wall -W -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtScript -I/usr/include -I../extra/qhexedit2/src -I. -I. -o moc_pdmlreader.o moc_pdmlreader.cpp
    fileformat.pb.cc: In member function 'virtual google::protobuf::uint8* OstProto::FileChecksum::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
    fileformat.pb.cc:3105:10: warning: unused parameter 'deterministic' [-Wunused-parameter]
         bool deterministic, ::google::protobuf::uint8* target) const {
              ^~~~~~~~~~~~~
    ...
    g++ -c -pipe -O2 -D_REENTRANT -Wall -W -DHAVE_REMOTE -DWPCAP -DHAVE_IFLA_STATS64 -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtScript -I/usr/include -I../rpc -I. -o pcapextra.o pcapextra.cpp
    echo "const char *version = \"0.7.1\"; const char *revision = \"da551b378f72@\";" > version.cpp
    /usr/bin/moc -DHAVE_REMOTE -DWPCAP -DHAVE_IFLA_STATS64 -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtScript -I/usr/include -I../rpc -I. drone.h -o moc_drone.cpp
    /usr/bin/moc -DHAVE_REMOTE -DWPCAP -DHAVE_IFLA_STATS64 -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtScript -I/usr/include -I../rpc -I. myservice.h -o moc_myservice.cpp
    In file included from /usr/include/pcap.h:43:0,
                     from pcapextra.h:23,
                     from pcapextra.cpp:20:
    /usr/include/pcap/pcap.h:531:26: fatal error: remote-ext.h: No such file or directory
       #include <remote-ext.h>
                              ^
    compilation terminated.
    make[1]: *** [Makefile.drone:309: pcapextra.o] Error 1
    make[1]: *** Waiting for unfinished jobs....
    In file included from /usr/include/pcap.h:43:0,
                     from pcapport.h:25,
                     from pcapport.cpp:20:
    /usr/include/pcap/pcap.h:531:26: fatal error: remote-ext.h: No such file or directory
       #include <remote-ext.h>
                              ^
    compilation terminated.
    make[1]: *** [Makefile.drone:278: pcapport.o] Error 1
    In file included from /usr/include/pcap.h:43:0,
                     from pcapport.h:25,
                     from linuxport.h:27,
                     from linuxport.cpp:20:
    /usr/include/pcap/pcap.h:531:26: fatal error: remote-ext.h: No such file or directory
       #include <remote-ext.h>
                              ^
    compilation terminated.
    make[1]: *** [Makefile.drone:290: linuxport.o] Error 1
    In file included from /usr/include/pcap.h:43:0,
                     from pcapport.h:25,
                     from linuxport.h:27,
                     from portmanager.cpp:23:
    /usr/include/pcap/pcap.h:531:26: fatal error: remote-ext.h: No such file or directory
       #include <remote-ext.h>
                              ^
    compilation terminated.
    make[1]: *** [Makefile.drone:268: portmanager.o] Error 1
    abstractport.cpp: In member function 'void AbstractPort::updatePacketListSequential()':
    abstractport.cpp:245:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("ibg1 = %" PRIu64, ibg1);
                                               ^
    abstractport.cpp:246:42: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("nb1  = %" PRIu64, nb1);
                                              ^
    abstractport.cpp:247:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("ibg2 = %" PRIu64, ibg2);
                                               ^
    abstractport.cpp:248:47: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("nb2  = %" PRIu64 "\n", nb2);
                                                   ^
    abstractport.cpp:251:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("ipg1 = %" PRIu64, ipg1);
                                               ^
    abstractport.cpp:252:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("npx1 = %" PRIu64, npx1);
                                               ^
    abstractport.cpp:253:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("npy1 = %" PRIu64, npy1);
                                               ^
    abstractport.cpp:254:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("ipg2 = %" PRIu64, ipg2);
                                               ^
    abstractport.cpp:255:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("npx2 = %" PRIu64, npx2);
                                               ^
    abstractport.cpp:256:48: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                 qDebug("npy2 = %" PRIu64 "\n", npy2);
                                                    ^
    abstractport.cpp: In member function 'void AbstractPort::updatePacketListInterleaved()':
    abstractport.cpp:415:40: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
             qDebug("ibg1 = %" PRIu64, _ibg1);
                                            ^
    abstractport.cpp:416:39: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
             qDebug("nb1  = %" PRIu64, _nb1);
                                           ^
    abstractport.cpp:417:40: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
             qDebug("ibg2 = %" PRIu64, _ibg2);
                                            ^
    abstractport.cpp:418:44: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
             qDebug("nb2  = %" PRIu64 "\n", _nb2);
                                                ^
    abstractport.cpp:421:40: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
             qDebug("ipg1 = %" PRIu64, _ipg1);
                                            ^
    abstractport.cpp:422:39: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
             qDebug("np1  = %" PRIu64, _np1);
                                           ^
    abstractport.cpp:423:40: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
             qDebug("ipg2 = %" PRIu64, _ipg2);
                                            ^
    abstractport.cpp:424:44: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
             qDebug("np2  = %" PRIu64 "\n", _np2);
                                                ^
    abstractport.cpp:485:41: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
         qDebug("minGap   = %" PRIu64, minGap);
                                             ^
    abstractport.cpp:486:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
         qDebug("duration = %" PRIu64, duration);
                                               ^
    abstractport.cpp:521:79: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
                     qDebug("q(%d) sec = %" PRIu64 " nsec = %" PRIu64, i, sec, nsec);
                                                                                   ^
    abstractport.cpp:521:79: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'quint64 {aka long long unsigned int}' [-Wformat=]
    abstractport.cpp:561:68: warning: format '%ld' expects argument of type 'long int', but argument 2 has type 'qint64 {aka long long int}' [-Wformat=]
         qDebug("loop Delay = %" PRId64 "/%" PRId64, delaySec, delayNsec);
                                                                        ^
    abstractport.cpp:561:68: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'qint64 {aka long long int}' [-Wformat=]
    make[1]: Leaving directory '/home/jirutjak/aports/testing/ostinato/src/ostinato-0.7.1/server'
    make: *** [Makefile:189: sub-server-drone-pro-make_default-ordered] Error 2
    ```

### CODE REVIEW

**Comment by olanod** [comment]
Great that this package exist!, is the ruby stuff needed? also the current version of the package doesn't include some *.proto files that are placed in the `include` directory, usually found when downloading a normal release, does this update generates those files as well?

**Comment by jirutka** [comment]
Yes, it is needed, because the gem Google published on Rubygems is incredible messy, broken and insecure crap.

**Comment by jirutka** [comment]
This has been already merged.
