### PR TITLE
main/libical: fix db.h: No such file or directory

### PR DESCRIPTION
**Pull request by ollieparanoid**
Make libical-dev depend on db-dev, so db.h is available when building
against libical-dev.

Fix this error when building programs that depend on libical-dev:

```
In file included from /home/pmos/build/src/kcalcore-18.12.3/src/icalformat.cpp:45:
/usr/include/libical/icalss.h:492:10: fatal error: db.h: No such file or directory
 #include <db.h>
          ^~~~~~
```

---

I have verified that this fixes building kcalcore:
https://gitlab.com/postmarketOS/pmaports/issues/229

Regression from https://github.com/alpinelinux/aports/commit/e6ee35d11eca7f4d046efe106cc7d5c19d8c76b3 (CC @brebs-gh, @rnalrd)

### CODE REVIEW

File: main/libical/APKBUILD [hunk 1]
```diff
@@ -38,4 +38,12 @@ package() {
 	make DESTDIR="$pkgdir" install
 }
 
+# libical-dev needs db.h from db-dev, so depend on it
+# /usr/include/libical/icalss.h:492:10: fatal error: db.h: No such file or directory
+dev() {
+	default_dev
+	depends="$depends db-dev"
```
Comment (ncopa) [inline main/libical/APKBUILD]: `depends="$depends ..."` is problematic in split functions and should be avoided.
See http://lists.alpinelinux.org/alpine-devel/6582.html

Instead do:
````sh
depends_dev="db-dev"
makedepends="$depends_dev ..."
````

**Comment by ollieparanoid** [comment]
@ncopa: thanks for the review, updated. Do you want to merge it?
